basePath: /api
definitions:
  helpers.ErrorResponseJson:
    properties:
      message:
        type: string
      status:
        type: boolean
    type: object
  helpers.SuccessResponseJson:
    properties:
      message:
        type: string
      status:
        type: boolean
    type: object
  request.UserLogin:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  request.UserRegister:
    properties:
      email:
        type: string
      fullname:
        type: string
      password:
        type: string
      role:
        type: string
    required:
    - email
    - fullname
    - password
    - role
    type: object
  response.UserRegisterResponse:
    properties:
      email:
        type: string
      fullname:
        type: string
      id:
        type: string
    type: object
host: https://sariguna-backend.vercel.app
info:
  contact: {}
  title: Swagger Exampaaale API
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: Login user
      parameters:
      - description: Login
        in: body
        name: Login
        required: true
        schema:
          $ref: '#/definitions/request.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/helpers.SuccessResponseJson'
            - properties:
                data:
                  $ref: '#/definitions/response.UserRegisterResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ErrorResponseJson'
        "422":
          description: invalid payload
          schema:
            $ref: '#/definitions/helpers.ErrorResponseJson'
      summary: Login user
      tags:
      - Auth
  /user/register:
    post:
      consumes:
      - application/json
      description: Register user
      parameters:
      - description: Register
        in: body
        name: Register
        required: true
        schema:
          $ref: '#/definitions/request.UserRegister'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/helpers.SuccessResponseJson'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ErrorResponseJson'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/helpers.ErrorResponseJson'
      summary: Register user
      tags:
      - Auth
schemes:
- http
swagger: "2.0"
